#! /bin/bash


for ns in atg4g venturi-1 venturi-2; do
	NS="denter $ns"
	echo; echo; echo "====== NAMESPACE $ns =========="
	echo; echo "------- addresses  -------------"
	$NS ip -o -4 addr ls

	echo; echo "------- Firewall    -------------"
	for chain in PREROUTING OUTPUT; do
		label=$(printf "|%-12.12s|" "$chain")
		echo; echo "-------${label}-------------" 
		for table in raw mangle nat filter; do
			echo; echo "------- $table  -------------"
			$NS iptables -w -t $table -S $chain 2> /dev/null
		done| sed -e 's/^/\t/'
	done| sed -e 's/^/\t/'
	
	echo; echo "------- rules      -------------"
	$NS ip rule ls

	echo; echo "------- routes      -------------"
	for table in $($NS ip rule ls | awk '{print $NF}'); do
		echo; echo "------- $table routes    -------------"
		$NS ip route ls table $table
	done| sed -e 's/^/\t/'

	echo; echo "------- Firewall    -------------"
	for chain in INPUT FORWARD OUTPUT POSTROUTING; do
		label=$(printf "|%-10.10s|" "$chain")
		echo; echo "------- {$label} -------------" 
		for table in raw mangle nat filter; do
			echo; echo "------- $table  -------------"
			$NS iptables -w -t $table -S $chain 2> /dev/null
		done| sed -e 's/^/\t/'
	done| sed -e 's/^/\t/'
	
done
