#! /bin/bash


opt_t=

function usage() {
	echo "Usage: $(basename $0) options"
	echo "Options:"
	echo "-t tag                NFLOG tag"
	echo "-h                    Help(this message)"
}

while getopts "ht:-" opt ; do
        case "$opt" in
        -)  break ;;
        t)  opt_t=$OPTARG ;;
        h) usage; exit ;;
        esac
done

shift $(($OPTIND-1))
selector="$@"
if [[ -n $opt_t ]]; then
	TAG="${opt_t}-"
fi
iptables -t mangle -I PREROUTING  ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}PRE
iptables -t mangle -I INPUT       ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}INPUT
iptables -t mangle -I FORWARD     ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}FWD
iptables -t mangle -I OUTPUT      ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}OUT
iptables -t mangle -I POSTROUTING ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}POST
