#! /bin/bash


opt_t=

function usage() {
	echo "Usage: $(basename $0) options -- iptables-selector"
	echo "Options:"
	echo "-t table              iptables table"
	echo "-p prefix             NFLOG tag"
	echo "-h                    Help(this message)"
}

opt_t="filter"

while getopts "hp:t:-" opt ; do
        case "$opt" in
        -)  break ;;
        t)  opt_t=$OPTARG ;;
        p)  opt_p=$OPTARG ;;
        h) usage; exit ;;
        esac
done

if [ $# -lt 1 ]; then
	usage
	exit
fi

shift $(($OPTIND-2))
if [ $1 != "--" ] ; then
	usage
	exit
fi
shift

selector="$@"
if [[ -n $opt_p ]]; then
	TAG="${opt_p}-"
fi


case ${opt_t} in
	filter)
		INPUT=1; OUTPUT=1; FORWARD=1;
		;;
	mangle)
		INPUT=1; OUTPUT=1; FORWARD=1; PRE=1; POST=1;
		;;
	nat)
		OUTPUT=1; FORWARD=1; PRE=1; POST=1;
		;;
	raw)
		OUTPUT=1; PRE=1;
		;;
esac

[[ $PRE ]] && iptables -t ${opt_t} -A PREROUTING  ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}PRE
[[ $INPUT ]] && iptables -t ${opt_t} -A INPUT       ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}INPUT
[[ $FORWARD ]] && iptables -t ${opt_t} -A FORWARD     ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}FWD
[[ $OUTPUT ]] && iptables -t ${opt_t} -A OUTPUT      ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}OUT
[[ $POST ]] && iptables -t ${opt_t} -A POSTROUTING ${selector} -j NFLOG --nflog-group 2 --nflog-prefix ${TAG}POST
