#! /bin/bash


for ns in router hosta hostb hostc ; do
	ip netns del $ns
	ip netns add $ns
	ip link add ${ns}-in type veth peer name ${ns}-out
	ip link set ${ns}-in netns $ns name $ns up
	case "$ns" in
	router)
		ip link set ${ns}-out name $ns up
		;;
	hosta|hostb|hostc)
		ip link set ${ns}-out netns router name $ns up
		;;
	esac
	ip netns exec $ns ip link set lo up
	ip netns exec $ns bash -c "echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts"

done

INR="ip netns exec router"
INA="ip netns exec hosta"
INB="ip netns exec hostb"
INC="ip netns exec hostc"


$INR brctl addbr int-cabin
$INR brctl addif int-cabin hosta
$INR ip link set int-cabin up
$INR ip addr add 172.20.10.1/24 dev int-cabin
$INR ip addr add 192.168.1.61/24 dev hostb
$INR ip link set hostb multicast off
$INR ip addr add 192.168.51.1/16 dev hostc
$INR bash -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

$INR ./sniff-mangle

# HostA is downstream
$INA ip addr add 172.20.10.100/24 dev hosta
$INA ip route add default via 172.20.10.1
 
# HostB is upstream
$INB ip addr add 192.168.1.15/24 dev hostb

# HostC is a static route provider with an overlapping address space
$INC ip addr add 192.168.4.1/16 dev hostc
$INC ip addr add 224.0.0.0/4 dev hostc

